/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.show_do_javao.view;

import com.mycompany.show_do_javao.controller.PerguntaController;
import com.mycompany.show_do_javao.service.BancoPerguntas;

import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Luut
 */
public class TelaPerguntas extends javax.swing.JFrame {

    ImageIcon icon = new ImageIcon(getClass().getResource("/SdMLogo.png"));
    JLabel fundo = new JLabel(icon);
    ArrayList<JTextField> buttons = new ArrayList<>();
    BancoPerguntas perguntas;
    String respostaV;
    String respostaE;
    int dinheiro = 1;

    /**
     * Creates new form NewJFrame
     */
    public TelaPerguntas() {
        this.setResizable(false);
        this.setVisible(true);
        initComponents();
        this.perguntas = new BancoPerguntas();
        this.setLocationRelativeTo(null);
        pergunta.setEditable(false);
        pergunta.setFocusable(false);
        resposta1.setEditable(false);
        resposta1.setFocusable(false);
        resposta2.setEditable(false);
        resposta2.setFocusable(false);
        resposta3.setEditable(false);
        resposta3.setFocusable(false);
        resposta4.setEditable(false);
        resposta4.setFocusable(false);
        escolher.setEditable(false);
        escolher.setFocusable(false);
        parar.setEditable(false);
        parar.setFocusable(false);
        ajuda.setEditable(false);
        ajuda.setFocusable(false);
        icon.setImage(icon.getImage().getScaledInstance(logo.getWidth(), logo.getHeight(), 2));
        logo.setIcon(icon);
        buttons.add(resposta1);
        buttons.add(resposta2);
        buttons.add(resposta3);
        buttons.add(resposta4);
        this.respostaV = PerguntaController.getPergunta(perguntas, pergunta, resposta1, resposta2, resposta3, resposta4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        pergunta = new javax.swing.JTextField();
        resposta1 = new javax.swing.JTextField();
        resposta2 = new javax.swing.JTextField();
        resposta3 = new javax.swing.JTextField();
        resposta4 = new javax.swing.JTextField();
        escolher = new javax.swing.JTextField();
        parar = new javax.swing.JTextField();
        ajuda = new javax.swing.JTextField();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 29, 147));

        pergunta.setBackground(new java.awt.Color(153, 0, 0));
        pergunta.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        pergunta.setForeground(new java.awt.Color(255, 255, 255));
        pergunta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pergunta.setText("Pergunta 1");
        pergunta.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 51, 0), new java.awt.Color(153, 51, 0)));
        pergunta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pergunta.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        resposta1.setBackground(new java.awt.Color(255, 0, 0));
        resposta1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        resposta1.setForeground(new java.awt.Color(255, 255, 255));
        resposta1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        resposta1.setText("Resposta 1");
        resposta1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 51, 0), new java.awt.Color(153, 51, 0)));
        resposta1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resposta1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        resposta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resposta1MouseClicked(evt);
            }
        });

        resposta2.setBackground(new java.awt.Color(255, 0, 0));
        resposta2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        resposta2.setForeground(new java.awt.Color(255, 255, 255));
        resposta2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        resposta2.setText("Resposta 2");
        resposta2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 51, 0), new java.awt.Color(153, 51, 0)));
        resposta2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resposta2.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        resposta2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resposta2MouseClicked(evt);
            }
        });

        resposta3.setBackground(new java.awt.Color(255, 0, 0));
        resposta3.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        resposta3.setForeground(new java.awt.Color(255, 255, 255));
        resposta3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        resposta3.setText("Resposta 3");
        resposta3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 51, 0), new java.awt.Color(153, 51, 0)));
        resposta3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resposta3.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        resposta3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resposta3MouseClicked(evt);
            }
        });

        resposta4.setBackground(new java.awt.Color(255, 0, 0));
        resposta4.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        resposta4.setForeground(new java.awt.Color(255, 255, 255));
        resposta4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        resposta4.setText("Resposta 4");
        resposta4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 51, 0), new java.awt.Color(153, 51, 0)));
        resposta4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resposta4.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        resposta4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resposta4MouseClicked(evt);
            }
        });

        escolher.setBackground(new java.awt.Color(255, 204, 0));
        escolher.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        escolher.setForeground(new java.awt.Color(204, 0, 0));
        escolher.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        escolher.setText("ESCOLHER");
        escolher.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 51, 0), new java.awt.Color(153, 51, 0)));
        escolher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        escolher.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        escolher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escolherMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                escolherMousePressed(evt);
            }
        });

        parar.setBackground(new java.awt.Color(255, 204, 0));
        parar.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        parar.setForeground(new java.awt.Color(204, 0, 0));
        parar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        parar.setText("PARAR");
        parar.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 51, 0), new java.awt.Color(153, 51, 0)));
        parar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        parar.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        parar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pararMouseClicked(evt);
            }
        });

        ajuda.setBackground(new java.awt.Color(255, 204, 0));
        ajuda.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ajuda.setForeground(new java.awt.Color(204, 0, 0));
        ajuda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ajuda.setText("AJUDA");
        ajuda.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 51, 0), new java.awt.Color(153, 51, 0)));
        ajuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ajuda.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        ajuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajudaMouseClicked(evt);
            }
        });
        ajuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajudaActionPerformed(evt);
            }
        });

        logo.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(pergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(escolher, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(parar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ajuda, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resposta4, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resposta3, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resposta2, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resposta1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(resposta1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(resposta2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(resposta3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(resposta4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(escolher, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ajuda, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resposta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resposta1MouseClicked
        colorBlue(resposta1);
        respostaE = resposta1.getText();// TODO add your handling code here:
    }//GEN-LAST:event_resposta1MouseClicked

    private void escolherMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escolherMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_escolherMousePressed

    private void escolherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escolherMouseClicked
        if (respostaE.equals(respostaV)) {
            this.respostaV = PerguntaController.getPergunta(perguntas, pergunta, resposta1, resposta2, resposta3, resposta4);
            colorRed();
            dinheiro *= 2;
            
            if(dinheiro > 1000) {
                 new TelaVitoria().setVisible(true);
                 this.dispose();
            }
        } else {
            pergunta.setText("ERROU");
            colorRed();
        }// TODO add your handling code here:
    }//GEN-LAST:event_escolherMouseClicked

    private void resposta2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resposta2MouseClicked
        colorBlue(resposta2);
        respostaE = resposta2.getText();// TODO add your handling code here:
    }//GEN-LAST:event_resposta2MouseClicked

    private void resposta3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resposta3MouseClicked
        colorBlue(resposta3);
        respostaE = resposta3.getText();// TODO add your handling code here:
    }//GEN-LAST:event_resposta3MouseClicked

    private void resposta4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resposta4MouseClicked
        colorBlue(resposta4);
        respostaE = resposta4.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_resposta4MouseClicked

    private void ajudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajudaActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_ajudaActionPerformed

    private void ajudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajudaMouseClicked
       new TelaAjuda().setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_ajudaMouseClicked

    private void pararMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pararMouseClicked
        int reply = JOptionPane.showConfirmDialog(this, "Deseja realmente parar?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION)
        {
          new TelaInicial().setVisible(true);
          this.dispose();
        }
    }//GEN-LAST:event_pararMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPerguntas().setVisible(true);
            }
        });
    }

    private void colorBlue(JTextField label) {
        buttons.forEach(button -> {
            if (button.getText().equals(label.getText())) {
                label.setBackground(Color.BLUE); // Verde claro com transparência
                label.setOpaque(true);
            } else {
                button.setBackground(Color.RED);
            }

        });    
    }
    private void colorRed() {
        buttons.forEach(button -> {button.setBackground(Color.RED);});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ajuda;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField escolher;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField parar;
    private javax.swing.JTextField pergunta;
    private javax.swing.JTextField resposta1;
    private javax.swing.JTextField resposta2;
    private javax.swing.JTextField resposta3;
    private javax.swing.JTextField resposta4;
    // End of variables declaration//GEN-END:variables
}
