/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.show_do_javao.view;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Aluno
 */
public class TelaPerguntas extends javax.swing.JFrame {
ImageIcon icon = new ImageIcon(getClass().getResource("/imagemPerguntas.png"));
JLabel fundo = new JLabel(icon);
    /**
     * Creates new form TelaPerguntas
     */
    public TelaPerguntas() {
        this.setResizable(false);
        this.setVisible(true);
        initComponents();
        this.setLocationRelativeTo(null);
        icon.setImage(icon.getImage().getScaledInstance(this.getWidth(), this.getHeight(), 2));
        this.setContentPane(fundo);
        fundo.setLayout(null);
        fundo.add(labelPergunta);
        //Cor do botão A
        botaoA.setOpaque(false);
        botaoA.setContentAreaFilled(false);
        botaoA.setBorderPainted(false);
        botaoA.setForeground(Color.WHITE);
        add(botaoA);
        //Cor do botão B
        botaoB.setOpaque(false);
        botaoB.setContentAreaFilled(false);
        botaoB.setBorderPainted(false);
        botaoB.setForeground(Color.WHITE);
        add(botaoB);
        //Cor do botão C
        botaoC.setOpaque(false);
        botaoC.setContentAreaFilled(false);
        botaoC.setBorderPainted(false);
        botaoC.setForeground(Color.WHITE);
        add(botaoC);
        //Cor do botão D
        botaoD.setOpaque(false);
        botaoD.setContentAreaFilled(false);
        botaoD.setBorderPainted(false);
        botaoD.setForeground(Color.WHITE);
        add(botaoD);
         //Cor do botão ESCOLHER
        btnEscolher.setOpaque(false);
        btnEscolher.setContentAreaFilled(false);
        btnEscolher.setBorderPainted(false);
        btnEscolher.setForeground(Color.RED);
        add(btnEscolher);
         //Cor do botão PARAR
        btnParar.setOpaque(false);
        btnParar.setContentAreaFilled(false);
        btnParar.setBorderPainted(false);
        btnParar.setForeground(Color.RED);
        add(btnParar);
         //Cor do botão AJUDA
        btnAjuda.setOpaque(false);
        btnAjuda.setContentAreaFilled(false);
        btnAjuda.setBorderPainted(false);
        btnAjuda.setForeground(Color.RED);
        add(btnAjuda);
        //Label indicador das opções
        
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPergunta = new javax.swing.JLabel();
        botaoA = new javax.swing.JButton();
        botaoB = new javax.swing.JButton();
        botaoC = new javax.swing.JButton();
        botaoD = new javax.swing.JButton();
        btnEscolher = new javax.swing.JButton();
        btnParar = new javax.swing.JButton();
        btnAjuda = new javax.swing.JButton();
        C = new javax.swing.JLabel();
        D = new javax.swing.JLabel();
        B = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelPergunta.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelPergunta.setForeground(new java.awt.Color(255, 255, 255));
        labelPergunta.setText("Se seu pinto for maior que seu antebraço, qual animal você é?");

        botaoA.setText("Golfinho");
        botaoA.setBorder(null);
        botaoA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botaoAMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                botaoAMouseReleased(evt);
            }
        });
        botaoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAActionPerformed(evt);
            }
        });

        botaoB.setText("Gremista");
        botaoB.setBorder(null);
        botaoB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoBMouseClicked(evt);
            }
        });

        botaoC.setText("Roxo");
        botaoC.setBorder(null);
        botaoC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCMouseClicked(evt);
            }
        });

        botaoD.setText("Tamanduá-Bandeira");
        botaoD.setBorder(null);
        botaoD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoDMouseClicked(evt);
            }
        });

        btnEscolher.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        btnEscolher.setForeground(new java.awt.Color(255, 0, 0));
        btnEscolher.setText("ESCOLHER");
        btnEscolher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnParar.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        btnParar.setForeground(new java.awt.Color(255, 51, 51));
        btnParar.setText("PARAR");
        btnParar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnAjuda.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        btnAjuda.setForeground(new java.awt.Color(255, 0, 0));
        btnAjuda.setText("AJUDA");
        btnAjuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        C.setText("A");

        D.setText("A");

        B.setText("A");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEscolher, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnParar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAjuda, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(B, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botaoD, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(botaoC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botaoB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                                        .addComponent(botaoA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addGap(112, 445, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(labelPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoA, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoB, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoC, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoD, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEscolher, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnParar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAjuda, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAActionPerformed
    
           botaoA.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                botaoA.setBackground(new Color(0, 255, 0, 100)); // Verde translúcido
                botaoA.setOpaque(true);
                botaoA.setContentAreaFilled(true);
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                botaoA.setOpaque(false);
                botaoA.setContentAreaFilled(false);
            }
        });

      
       // TODO add your handling code here:
    }//GEN-LAST:event_botaoAActionPerformed

    private void botaoAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAMousePressed
botaoA.setBackground(new Color(0, 255, 0, 50)); // Verde claro com transparência
botaoA.setOpaque(true);
//botaoA.setContentAreaFilled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_botaoAMousePressed

    private void botaoAMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAMouseReleased
    // TODO add your handling code here:
    }//GEN-LAST:event_botaoAMouseReleased

    private void botaoBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoBMouseClicked
botaoB.setBackground(new Color(0, 255, 0, 50)); // Verde claro com transparência
botaoB.setOpaque(true);        // TODO add your handling code here:
    }//GEN-LAST:event_botaoBMouseClicked

    private void botaoCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCMouseClicked
botaoC.setBackground(new Color(0, 255, 0, 50)); // Verde claro com transparência
botaoC.setOpaque(true);        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCMouseClicked

    private void botaoDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoDMouseClicked
botaoD.setBackground(new Color(0, 255, 0, 50)); // Verde claro com transparência
botaoD.setOpaque(true);        // TODO add your handling code here:
    }//GEN-LAST:event_botaoDMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPerguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPerguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel B;
    private javax.swing.JLabel C;
    private javax.swing.JLabel D;
    private javax.swing.JButton botaoA;
    private javax.swing.JButton botaoB;
    private javax.swing.JButton botaoC;
    private javax.swing.JButton botaoD;
    private javax.swing.JButton btnAjuda;
    private javax.swing.JButton btnEscolher;
    private javax.swing.JButton btnParar;
    private javax.swing.JLabel labelPergunta;
    // End of variables declaration//GEN-END:variables
}
